apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: postgres-pv-claim  
  containers:
      - name: postgres-container
        image: rimalroshan/postgres
        volumeMounts:
          - mountPath: "/var/lib/postgres/data"
            name: myvol