apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lft
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /pv/postgres